[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
env_logger = "0.11.8"
tcio = { version = "0.1.0", path = "../tcio", features = ["log", "tokio"] }
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
